version: '3.8'
services:
  php-logger:
    image: radosz88/php-logger:latest
    container_name: php-logger
    ports:
      - "9000:9000"
    environment:
      - LOGS_DIR=/app/logs
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
